
# This handles building the project

compiler: clang++ # Change to whatever will compile your c/c++ code. You can even use emscripten!
name: Constellations # The name of the project, used for debugging.
output: constellations # The output file.

# These are the flags that will be passed to the compiler, such as -std=c++17
flags: 
    - std=c++17
    - framework CoreVideo
    - framework IOKit
    - framework Cocoa
    - framework GLUT
    - framework OpenGL

# The c/c++ files that will be compiled in order. 
files: 
    - src/libraylib.a
    - src/components/object.cpp
    - src/components/drag.cpp
    - src/main.cpp

# Where are the header files located?
includes:
   - raylib/src
   - src/components

# Not to be confused with libraries, these are the paths to the libraries.
# libs:
#     - 

# These are the libraries that will be linked to the project. Path must be specified in libs.
# libraries: 
#    - raylib

# Shell commands to run before or after building.
# This is more (CMake) style, where you can run shell commands before building. 
# Also, you can run shell commands after building.
shell:
    # before:
    #     - echo "Hello, world!"
    after:
        - ./constellations # Usually you want to run the program after building it.

